### ISSUE TITLE
searching

### ISSUE THREAD

**Issue by tsrfuj** [GregoryWullimann/FUTBoost#1]
When i press the shortcut for searching and its assigned to S, the page goes down to preset 3. also when i try to search with mouse, some strange cards appear with no rating or anything. also when i try to search icons only, nothing appear.

**Comment by tsrfuj** [comment]
also i think the load preset not working it only save

**Comment by GregoryWullimann** [comment]
> When i press the shortcut for searching and its assigned to S, the page goes down to preset 3. 
> also i think the load preset not working it only save

Hi,

thanks for reporting the issue. This has been fixed and will be soon avaiable on the next version of the extension.

> also when i try to search with mouse, some strange cards appear with no rating or anything. also when i try to search icons only, nothing appear.

If you see no results it's because on that page there are no icons or cards that valid for the filter you set. If you go to through the next pages you should see more results.

The extension only hides the "bad" results

**Comment by tsrfuj** [comment]
> If you see no results it's because on that page there are no icons or cards that valid for the filter you set. If you go to through the next pages you should see more results.
> 
> The extension only hides the "bad" results

Thank you for responding.
I only tried to search with only icons selected, i thought this should make only all listed icons in the market appear. But nothing appeared.

**Comment by tsrfuj** [comment]
Also about that strange card that appears when i search.
Can this card stop appearing? I mean when i search for something and its not listed in market i get that no search results instead?

**Comment by GregoryWullimann** [comment]
> > If you see no results it's because on that page there are no icons or cards that valid for the filter you set. If you go to through the next pages you should see more results.
> > The extension only hides the "bad" results
> 
> Thank you for responding.
> I only tried to search with only icons selected, i thought this should make only all listed icons in the market appear. But nothing appeared.

Unfortunately the way the web app works first a normal search is made (with the normally available parameters like Buy Price, position, etc.), so what the extension does is that it hides the bad results, that's why you get empty pages. By the way, for Icons you can use the normal filter, there is a league called "Icons" :)



> Also about that strange card that appears when i search.
> Can this card stop appearing? I mean when i search for something and its not listed in market i get that no search results instead?

I guess you are talking about this image? https://i.imgur.com/g410NLR.png

You should only see it on the right side and not in the full list, right? This also can't be removed because of the same thing that I explained above.

**Comment by tsrfuj** [comment]
I saw other filters like this but that strange card dont appear so what's difference?

And yes i only see it on the right side but it can be bought so i can buy it with mistake.

I also tried to search for only headliners but nothing appear.
Thanks.

**Comment by GregoryWullimann** [comment]
The other filters that I have seen show the real card instead a "fake" one, so it is just a matter of implementation.
